"""Small YAML loading compatibility layer for bundled CLI tools.

The skill installer copies these tools without Python package dependencies. Use
PyYAML when it is available, and fall back to a small parser that supports the
metadata and task-list shapes generated by this workflow.
"""

from __future__ import annotations

import json
import os
import site
import subprocess
import sys
import sysconfig
import venv
from pathlib import Path
from typing import Any, List, Tuple

try:
    import yaml  # type: ignore
except ImportError:  # pragma: no cover - exercised in dependency-light installs
    yaml = None


def _try_install_pyyaml() -> bool:
    """Best-effort install for users, with fallback if installation fails."""
    if os.environ.get('MAW_DISABLE_AUTO_INSTALL') == '1':
        return False

    commands = [
        [sys.executable, '-m', 'pip', 'install', '--quiet', 'PyYAML'],
        [sys.executable, '-m', 'pip', 'install', '--quiet', '--user', 'PyYAML'],
    ]

    for command in commands:
        try:
            subprocess.run(
                command,
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=120,
            )
            return True
        except Exception:
            continue

    return _install_pyyaml_into_managed_venv()


def _install_pyyaml_into_managed_venv() -> bool:
    venv_dir = Path(
        os.environ.get(
            'MAW_PYTHON_ENV',
            str(Path.home() / '.cache' / 'multi-agent-workflow' / 'python-env'),
        )
    )

    try:
        if not venv_dir.exists():
            venv.EnvBuilder(with_pip=True, clear=False).create(venv_dir)

        python = venv_dir / ('Scripts/python.exe' if os.name == 'nt' else 'bin/python')
        subprocess.run(
            [str(python), '-m', 'pip', 'install', '--quiet', 'PyYAML'],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=180,
        )

        purelib = subprocess.check_output(
            [
                str(python),
                '-c',
                'import sysconfig; print(sysconfig.get_paths()["purelib"])',
            ],
            text=True,
        ).strip()
        platlib = subprocess.check_output(
            [
                str(python),
                '-c',
                'import sysconfig; print(sysconfig.get_paths()["platlib"])',
            ],
            text=True,
        ).strip()

        for path in [purelib, platlib, *site.getsitepackages(), sysconfig.get_paths().get('purelib', '')]:
            if path and path not in sys.path:
                sys.path.insert(0, path)
        return True
    except Exception:
        return False


def safe_load(source: Any) -> Any:
    """Load YAML-like content using PyYAML or a dependency-free fallback."""
    global yaml

    if yaml is not None:
        return yaml.safe_load(source)

    if _try_install_pyyaml():
        try:
            import yaml as installed_yaml  # type: ignore

            yaml = installed_yaml
            return yaml.safe_load(source)
        except ImportError:
            yaml = None

    text = source.read() if hasattr(source, 'read') else str(source)
    stripped = text.strip()
    if not stripped:
        return None
    if stripped[0] in '[{':
        return json.loads(stripped)

    lines = _prepare_lines(text)
    if not lines:
        return None
    value, _ = _parse_block(lines, 0, lines[0][0])
    return value


def _prepare_lines(text: str) -> List[Tuple[int, str]]:
    prepared: List[Tuple[int, str]] = []
    for raw in text.splitlines():
        line = raw.split('#', 1)[0].rstrip()
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip(' '))
        prepared.append((indent, line.strip()))
    return prepared


def _parse_block(lines: List[Tuple[int, str]], index: int, indent: int) -> Tuple[Any, int]:
    if index >= len(lines):
        return None, index
    if lines[index][1].startswith('- '):
        return _parse_list(lines, index, indent)
    return _parse_dict(lines, index, indent)


def _parse_dict(lines: List[Tuple[int, str]], index: int, indent: int) -> Tuple[dict, int]:
    result: dict = {}
    while index < len(lines):
        current_indent, content = lines[index]
        if current_indent < indent or content.startswith('- '):
            break
        if current_indent > indent:
            index += 1
            continue
        key, sep, value = content.partition(':')
        if not sep:
            index += 1
            continue
        key = key.strip()
        value = value.strip()
        index += 1
        if value:
            result[key] = _parse_scalar(value)
        elif index < len(lines) and lines[index][0] > current_indent:
            result[key], index = _parse_block(lines, index, lines[index][0])
        else:
            result[key] = {}
    return result, index


def _parse_list(lines: List[Tuple[int, str]], index: int, indent: int) -> Tuple[list, int]:
    result: list = []
    while index < len(lines):
        current_indent, content = lines[index]
        if current_indent < indent or not content.startswith('- '):
            break
        if current_indent > indent:
            index += 1
            continue

        item = content[2:].strip()
        index += 1
        if not item:
            if index < len(lines) and lines[index][0] > current_indent:
                value, index = _parse_block(lines, index, lines[index][0])
                result.append(value)
            else:
                result.append(None)
            continue

        if ':' in item and not item.startswith(('http://', 'https://')):
            key, _, value = item.partition(':')
            item_dict = {key.strip(): _parse_scalar(value.strip()) if value.strip() else {}}
            if index < len(lines) and lines[index][0] > current_indent:
                extra, index = _parse_dict(lines, index, lines[index][0])
                item_dict.update(extra)
            result.append(item_dict)
        else:
            result.append(_parse_scalar(item))
    return result, index


def _parse_scalar(value: str) -> Any:
    if value in ('true', 'True'):
        return True
    if value in ('false', 'False'):
        return False
    if value in ('null', 'Null', 'NULL', '~'):
        return None
    if (value.startswith('"') and value.endswith('"')) or (
        value.startswith("'") and value.endswith("'")
    ):
        return value[1:-1]
    if value.startswith('[') and value.endswith(']'):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [_parse_scalar(part.strip()) for part in inner.split(',')]
    try:
        return int(value)
    except ValueError:
        pass
    try:
        return float(value)
    except ValueError:
        return value
