# Multi-Agent Workflow Metrics Schema v1.0.0
# 定義三類指標，用於量化工作流執行品質

# 元數據
metadata:
  version: "1.0.0"
  description: "Multi-Agent Workflow 指標定義"
  created: "2026-01-24"

# ============================================================
# 執行指標 (Execution Metrics)
# 追蹤工作流執行的基本數據
# ============================================================
execution:
  duration_sec:
    type: number
    unit: seconds
    description: "階段執行時間（秒）"
    aggregation: sum

  agent_success_rate:
    type: percentage
    range: [0, 100]
    description: "Agent 成功完成率"
    formula: "(successful_agents / total_agents) * 100"

  retry_count:
    type: integer
    min: 0
    description: "重試次數"
    aggregation: sum

  token_usage:
    type: object
    description: "Token 使用量（預留）"
    properties:
      input_tokens:
        type: integer
        description: "輸入 token 數"
      output_tokens:
        type: integer
        description: "輸出 token 數"
      total_tokens:
        type: integer
        description: "總 token 數"

# ============================================================
# 品質指標 (Quality Metrics)
# 追蹤審查和驗證的品質數據
# ============================================================
quality:
  issues_found:
    type: integer
    min: 0
    description: "發現的問題總數"
    aggregation: sum

  by_severity:
    type: object
    description: "按嚴重程度分類的問題數"
    properties:
      blocker:
        type: integer
        description: "阻塞級問題（必須修復才能繼續）"
      high:
        type: integer
        description: "高優先級問題（應盡快修復）"
      medium:
        type: integer
        description: "中優先級問題（建議修復）"
      low:
        type: integer
        description: "低優先級問題（可選修復）"

  false_positive_rate:
    type: percentage
    range: [0, 100]
    description: "誤報率"
    formula: "(false_positives / total_issues) * 100"
    target: "<10%"

# ============================================================
# 效率指標 (Efficiency Metrics)
# 追蹤工作流效率和迭代數據
# ============================================================
efficiency:
  first_pass_success:
    type: boolean
    description: "首次執行是否成功"

  rollback_count:
    type: integer
    min: 0
    description: "回退次數"
    target: 0

  total_iterations:
    type: integer
    min: 1
    description: "總迭代次數"
    target: 1

  pass_at_k:
    type: object
    description: "第 k 次通過率"
    properties:
      pass_at_1:
        type: boolean
        description: "第 1 次嘗試是否通過"
      pass_at_2:
        type: boolean
        description: "第 2 次嘗試是否通過"
      pass_at_3:
        type: boolean
        description: "第 3 次嘗試是否通過"
      k:
        type: integer
        description: "實際通過時的嘗試次數"

# ============================================================
# 階段指標結構 (Stage Metrics Structure)
# 每個階段（RESEARCH/PLAN/IMPLEMENT/REVIEW/VERIFY）都有這些指標
# ============================================================
stage_template:
  stage_id:
    type: string
    enum: [research, plan, implement, review, verify]

  started_at:
    type: timestamp
    format: "ISO8601"

  ended_at:
    type: timestamp
    format: "ISO8601"

  duration_sec:
    type: number
    derived: true
    formula: "ended_at - started_at"

  perspectives:
    type: array
    description: "各視角的執行數據"
    items:
      perspective_id:
        type: string
      status:
        type: string
        enum: [pending, running, completed, failed, skipped]
      duration_sec:
        type: number
      output_path:
        type: string

  execution:
    $ref: "#/execution"

  quality:
    $ref: "#/quality"
    description: "僅 REVIEW/VERIFY 階段使用"

  efficiency:
    $ref: "#/efficiency"

# ============================================================
# 完整工作流指標結構 (Full Workflow Metrics)
# ============================================================
workflow_metrics:
  workflow_id:
    type: string
    format: "uuid"
    description: "工作流唯一識別碼"

  task:
    type: string
    description: "任務描述"

  started_at:
    type: timestamp

  ended_at:
    type: timestamp

  total_duration_sec:
    type: number

  status:
    type: string
    enum: [running, completed, failed, cancelled]

  stages:
    type: array
    items:
      $ref: "#/stage_template"

  summary:
    type: object
    description: "彙總指標"
    properties:
      total_agents:
        type: integer
      successful_agents:
        type: integer
      total_issues:
        type: integer
      blockers:
        type: integer
      total_rollbacks:
        type: integer
      final_pass_at_k:
        type: integer

# ============================================================
# 行動日誌指標 (Action Log Metrics)
# 追蹤工具調用層級的詳細數據
# ============================================================
action_logs:
  # 單一行動記錄結構
  action_entry:
    id:
      type: string
      format: "act_{timestamp}_{random}"
      description: "唯一識別碼"

    timestamp:
      type: string
      format: "ISO8601"
      description: "執行時間"

    workflow_id:
      type: string
      description: "工作流 ID"

    agent_id:
      type: string
      description: "執行的 Agent"

    stage:
      type: string
      enum: [RESEARCH, PLAN, TASKS, IMPLEMENT, REVIEW, VERIFY]
      description: "當前階段"

    tool:
      type: string
      enum: [Read, Edit, Write, Bash, Task, Glob, Grep, WebFetch, WebSearch]
      description: "工具名稱"

    status:
      type: string
      enum: [success, failed, timeout, skipped]
      description: "執行狀態"

    input:
      type: object
      description: "工具輸入參數（依工具類型不同）"

    output_preview:
      type: string
      max_length: 500
      description: "輸出預覽（截斷至 500 字元）"

    output_size:
      type: integer
      unit: bytes
      description: "完整輸出大小"

    error:
      type: string
      description: "錯誤訊息"

    stderr:
      type: string
      max_length: 1000
      description: "標準錯誤輸出（Bash 專用）"

    exit_code:
      type: integer
      description: "退出碼（Bash 專用）"

    duration_ms:
      type: integer
      unit: milliseconds
      description: "執行時間"

  # 各工具的 input 結構
  tool_input_schemas:
    Read:
      file_path:
        type: string
        description: "讀取的檔案路徑"

    Edit:
      file_path:
        type: string
      old_string:
        type: string
        max_length: 200
        description: "被替換的字串（截斷）"
      new_string:
        type: string
        max_length: 200
        description: "新字串（截斷）"

    Write:
      file_path:
        type: string
      content_size:
        type: integer
        description: "寫入內容大小"

    Bash:
      command:
        type: string
        max_length: 500
        description: "執行的命令"
      timeout:
        type: integer
        description: "超時設定（毫秒）"

    Task:
      subagent_type:
        type: string
        description: "子 Agent 類型"
      prompt:
        type: string
        max_length: 300
        description: "任務提示（截斷）"

    Glob:
      pattern:
        type: string
      path:
        type: string

    Grep:
      pattern:
        type: string
      path:
        type: string
      glob:
        type: string

    WebFetch:
      url:
        type: string

  # 彙總統計
  aggregated_stats:
    total_actions:
      type: integer
      description: "總行動數"

    by_tool:
      type: object
      description: "各工具的統計"
      properties:
        tool_name:
          type: string
        count:
          type: integer
        success_count:
          type: integer
        failed_count:
          type: integer
        avg_duration_ms:
          type: number
        total_duration_ms:
          type: integer

    by_status:
      type: object
      properties:
        success:
          type: integer
        failed:
          type: integer
        timeout:
          type: integer
        skipped:
          type: integer

    by_stage:
      type: object
      description: "各階段的行動統計"
      properties:
        stage_name:
          type: string
        action_count:
          type: integer
        failed_count:
          type: integer

    slowest_actions:
      type: array
      max_items: 10
      description: "最慢的 10 個行動"
      items:
        $ref: "#/action_logs/action_entry"

    recent_failures:
      type: array
      max_items: 20
      description: "最近 20 個失敗的行動"
      items:
        $ref: "#/action_logs/action_entry"

  # 日誌保留策略
  retention_policy:
    success_logs_days:
      type: integer
      default: 7
      description: "成功日誌保留天數"

    failed_logs_days:
      type: integer
      default: 30
      description: "失敗日誌保留天數"

    max_file_size_mb:
      type: integer
      default: 100
      description: "單個日誌檔案上限（MB）"
