workflow_id: clawdbot-auto-reply-_20260127_1725a0
topic: clawdbot-auto-reply-system
topic_display: Clawdbot 主動回報系統研究
stage: RESEARCH
created_at: 2026-01-27T03:21:30Z
completed_at: 2026-01-27T03:30:00Z

perspectives:
  - id: architecture
    name: 架構分析師
    model: sonnet
    status: completed
    focus: 系統結構、設計模式

  - id: cognitive
    name: 認知研究員
    model: sonnet
    status: completed
    focus: 方法論、思維框架

  - id: workflow
    name: 工作流設計師
    model: haiku
    status: completed
    focus: 執行流程、整合策略

  - id: industry
    name: 業界實踐專家
    model: haiku
    status: completed
    focus: 現有框架、最佳實踐

quality:
  consensus_rate: 0.90
  perspectives_completed: 4
  perspectives_expected: 4
  quality_score: 88

outputs:
  perspectives: perspectives/
  summaries: summaries/
  synthesis: synthesis.md
